# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmuxResurrect < Formula
  desc "Terminal workspace manager for cmux and Ghostty — save, restore, and template your workspaces"
  homepage "https://github.com/drolosoft/cmux-resurrect"
  version "1.9.7"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/drolosoft/cmux-resurrect/releases/download/v1.9.7/cmux-resurrect_1.9.7_darwin_amd64.tar.gz"
    sha256 "7b1993d3624acad8c2850ffd1307cbb1e49a2ebdc94072ca87808620a68c187f"

    define_method(:install) do
      bin.install "crex"
      bin.install_symlink "crex" => "cmux-resurrect"
      bash_completion.install "completions/crex.bash" => "crex"
      zsh_completion.install "completions/_crex"
      fish_completion.install "completions/crex.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/drolosoft/cmux-resurrect/releases/download/v1.9.7/cmux-resurrect_1.9.7_darwin_arm64.tar.gz"
    sha256 "62010d128f8d95c3254bea5d2cde56136d7e548b9b783aba826908cef69b6203"

    define_method(:install) do
      bin.install "crex"
      bin.install_symlink "crex" => "cmux-resurrect"
      bash_completion.install "completions/crex.bash" => "crex"
      zsh_completion.install "completions/_crex"
      fish_completion.install "completions/crex.fish"
    end
  end

  test do
    system "#{bin}/crex", "version"
    system "#{bin}/cmux-resurrect", "version"
  end
end
