# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmuxResurrect < Formula
  desc "Terminal workspace manager for cmux and Ghostty — save, restore, and template your workspaces"
  homepage "https://github.com/drolosoft/cmux-resurrect"
  version "1.15.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/drolosoft/cmux-resurrect/releases/download/v1.15.0/cmux-resurrect_1.15.0_darwin_amd64.tar.gz"
    sha256 "bc8e069456ebb87a90f3b80d37d5dc4dac21e4ef1ed833dcc5a295f24ce50962"

    define_method(:install) do
      bin.install "crex"
      bin.install_symlink "crex" => "cmux-resurrect"
      bash_completion.install "completions/crex.bash" => "crex"
      zsh_completion.install "completions/_crex"
      fish_completion.install "completions/crex.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/drolosoft/cmux-resurrect/releases/download/v1.15.0/cmux-resurrect_1.15.0_darwin_arm64.tar.gz"
    sha256 "33fc1838b08c2644aed0507a4c2b915cd7dfe3ac1912d4d0a841aa943072c08c"

    define_method(:install) do
      bin.install "crex"
      bin.install_symlink "crex" => "cmux-resurrect"
      bash_completion.install "completions/crex.bash" => "crex"
      zsh_completion.install "completions/_crex"
      fish_completion.install "completions/crex.fish"
    end
  end

  test do
    system "#{bin}/crex", "version"
    system "#{bin}/cmux-resurrect", "version"
  end
end
