# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmuxResurrect < Formula
  desc "Terminal workspace manager for cmux and Ghostty — save, restore, and template your workspaces"
  homepage "https://github.com/drolosoft/cmux-resurrect"
  version "1.25.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/drolosoft/cmux-resurrect/releases/download/v1.25.0/cmux-resurrect_1.25.0_darwin_amd64.tar.gz"
    sha256 "26d0a3d5ecd772bcd044099efa258755dfd0934e5a6275e190a528cae33e395b"

    define_method(:install) do
      bin.install "crex"
      bin.install_symlink "crex" => "cmux-resurrect"
      bash_completion.install "completions/crex.bash" => "crex"
      zsh_completion.install "completions/_crex"
      fish_completion.install "completions/crex.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/drolosoft/cmux-resurrect/releases/download/v1.25.0/cmux-resurrect_1.25.0_darwin_arm64.tar.gz"
    sha256 "e3ede703e031d48a3d1e8a9af0c6438cb52399e7d3878deca3a4b237c0e4c3a1"

    define_method(:install) do
      bin.install "crex"
      bin.install_symlink "crex" => "cmux-resurrect"
      bash_completion.install "completions/crex.bash" => "crex"
      zsh_completion.install "completions/_crex"
      fish_completion.install "completions/crex.fish"
    end
  end

  test do
    system "#{bin}/crex", "version"
    system "#{bin}/cmux-resurrect", "version"
  end
end
